language: go
go:
- '1.8'
script: echo "ok"
before_deploy:
  - env
  - sudo apt-get update -qq
  - sudo apt-get install -qq gettext-base
deploy:
  - provider: script
    skip_cleanup: true
    script: deploy.sh $TRAVIS_TAG
    on:
      tags: true
sudo: required
