language: go
go:
- '1.8'
script: env
before_deploy:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gettext-base
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      tags: true
sudo: required
