language: go
go:
- '1.8'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gettext-base
before_deploy: env
deploy:
  - provider: script
    skip_cleanup: true
    script: deploy.sh $TRAVIS_TAG
sudo: required
