apiVersion: v1
kind: Pod
metadata:
  name: node-stats
spec:
  volumes:
    - name: node-meminfo
      hostPath:
        path: /proc/meminfo
    - name: node-stat
      hostPath:
        path: /proc/stat
  containers:
    - name: node-stats
      image: alpine
      command: ["/bin/sleep","999999"]
      volumeMounts:
        - mountPath: /node-meminfo
          name: node-meminfo
      volumeMounts:
        - mountPath: /node-stat
          name: node-stat
      env:
        - name: MY_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
