apiVersion: v1
kind: Pod
metadata:
  name: api-test
spec:
  containers:
    - name: test
      image: alpine
      command: ["/bin/sleep","9000"]
      env:
        - name: MY_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
